version: "3.5"

services:
  hub:
    container_name: jp-hub
    build:
      context: ..
      dockerfile: ./Dockerfile
    networks:
      - frontend
    ports:
      - 8000:8000

  e2e:
    # ! Docker image version needs to be sync with the one in requirements_e2e.txt
    image: mcr.microsoft.com/playwright:v1.9.1-focal
    entrypoint: ["./e2e-tests/wait-for-it.sh", "hub:8000", "--strict", "--timeout=10", "--"]
    command: './e2e-tests/run_e2e.sh'
    networks:
      - frontend
    depends_on:
      - hub
    volumes:
      - $PWD:/tmp/papermill_report_src
    working_dir: /tmp/papermill_report_src

networks:
  frontend:
