version: "3.5"

services:
  hub:
    build:
      context: ..
      dockerfile: ./Dockerfile
    networks:
      - frontend
    ports:
      - 8000:8000

  e2e:
    # FIXME when https://github.com/microsoft/playwright-python/issues/338 is fixed, use official python-playwright image
    image: mcr.microsoft.com/playwright:focal
    entrypoint: ["./e2e-tests/wait-for-it.sh", "hub:8000", "--strict", "--timeout=10", "--"]
    command: './e2e-tests/run_e2e.sh'
    networks:
      - frontend
    depends_on:
      - hub
    volumes:
      - $PWD:/tmp/papermill_report_src
    working_dir: /tmp/papermill_report_src

networks:
  frontend:
