name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-3-7-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-3-7-
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: python -m pip install -r requirements.txt -r requirements_dev.txt
    - name: Lint package
      run: python -m flake8 papermill_report
    - name: Install package
      run: python -m pip install -e .
    - name: Test package
      run: |
        git config --global user.email "runner@github.action"
        git config --global user.name "GitHub CI"
        python -m pytest papermill_report
    - name: Integration tests
      run: |
        docker-compose -f "./e2e-tests/docker-compose.yml" down || true
        docker-compose -f "./e2e-tests/docker-compose.yml" pull
        docker-compose -f "./e2e-tests/docker-compose.yml" run --rm e2e ./e2e-tests/run_e2e.sh
    - name: Stop containers
      if: always()
      run: |
        # Print hub logs before removing the containers using the container name set in docker-compose file
        docker logs jp-hub
        docker-compose -f "./e2e-tests/docker-compose.yml" down
    - name: Upload screenshots and videos
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-tests
        path: ./.playwright
